version: "3.7"

services:
  server:
    image: nginx:stable-alpine
    depends_on:
      - php
      - mysql
      - redis
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - ticketing-software
  
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    env_file:
      - ./mysql/.env
    networks:
      - ticketing-software
  
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - ticketing-software

  composer:
    image: composer:2
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - ticketing-software
  
  npm:
    image: node:16
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    # entrypoint: ['npm']
    networks:
      - ticketing-software
    
  artisan:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - redis
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - ticketing-software 

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - ticketing-software
  
  queue:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: queue
    volumes:
      - ./src:/var/www/html
    depends_on:
      - server 
      - php
      - redis
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work --verbose --tries=3 --timeout=60
    networks:
      - ticketing-software 

networks:
  ticketing-software:
    